server:
  port: 9999

spring:
  datasource:
    url : jdbc:mysql://localhost:3306/testdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username : root
    password : 1234
  jpa: 
    hibernate.ddl-auto: update
    show-sql: true 